version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: claude_studio_postgres
    environment:
      POSTGRES_DB: claude_studio
      POSTGRES_USER: claude
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-development_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./web/server/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude -d claude_studio"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: claude_studio_postgres_data