name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Studio AI
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This helps us improve Studio AI for everyone.
        
        **Before submitting:** Please search existing issues to avoid duplicates.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I am using the latest version of Studio AI
          required: true
        - label: I have checked the documentation and troubleshooting guide
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute workflow '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened, include error messages
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: How are you running Studio AI?
      options:
        - Docker (recommended)
        - Local development
        - Cloud deployment
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Studio AI Version
      description: What version of Studio AI are you running?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser (if applicable)
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g., macOS 14.0, Ubuntu 22.04, Windows 11"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include relevant logs from:
        - Browser console (F12 → Console)
        - Server logs (`docker logs studio-ai-app` or terminal output)
        - Network tab (if API related)
      placeholder: Paste logs here...
      render: text
    validations:
      required: false

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Configuration (if applicable)
      description: If the bug is related to a specific workflow, please share the configuration
      placeholder: Paste workflow JSON or description here...
      render: json
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here:
        - Screenshots
        - Related issues
        - Workarounds you've tried
        - Impact on your use case
      placeholder: Any additional information that might help us understand the issue
    validations:
      required: false