name: Main Branch Protection

on:
  push:
    branches: [main]

jobs:
  ensure-pr:
    name: Ensure Changes via PR
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && !contains(github.event.head_commit.message, 'Merge pull request')
    
    steps:
    - name: Block Direct Push
      run: |
        echo "❌ Direct pushes to main branch are not allowed!"
        echo "Please create a pull request from a feature branch."
        exit 1